#!/bin/bash
if [ -z "$RER_ROOT" ]; then
    echo "Set an RER_ROOT environment variable" 1>&2
    exit 1
fi
if [ ! -d "$RER_ROOT" ]; then
    echo "RER_ROOT must point to a directory - \"${RER_ROOT}\$ does not" 1>&2
    exit 2
fi
if [ -f "${RER_ROOT}/cakey.pem" ]; then
    echo "${RER_ROOT}/cakey.pem already exists. Refusing to overwrite" 1>&2
    exit 3
fi
openssl req -x509 -config ./ca.cnf -newkey rsa:4096 -sha256 -nodes -batch -keyout "${RER_ROOT}/cakey.pem" -out "${RER_ROOT}/ca.crt"
touch "${RER_ROOT}/index.txt"
if [ ! -f "${RER_ROOT}/serial.txt" ]; then
    date "+%Y%m%d%H%M%S" > "${RER_ROOT}/serial.txt"
fi
