#!/bin/bash
if [ -z "$RER_ROOT" ]; then
    echo "Set an RER_ROOT environment variable" 1>&2
    exit 1
fi
if [ ! -d "$RER_ROOT" ]; then
    echo "RER_ROOT must point to a directory - \"${RER_ROOT}\$ does not" 1>&2
    exit 2
fi
if [ ! -f "${RER_ROOT}/cakey.pem" ]; then
    echo "${RER_ROOT}/cakey.pem does not exist. Use make-ca first." 1>&2
    exit 3
fi

OPTIND=1
prefix=""

while getopts "p:" opt; do
    case "$opt" in
	p) prefix=$OPTARG
	    ;;
    esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift

if [ ! -z "$@" ]; then
    echo "ERROR: Unknown trailing junk on command-line: \"$@\"" 1>&2
    exit 4
fi
csr="${prefix}.csr"
if [ ! -f "$csr" ]; then
    echo "ERROR: Must specify a valid prefix with -p" 1>&2
    exit 5
fi
out="${prefix}.crt"
openssl ca -config ./ca.cnf -policy signing_policy -batch -extensions signing_req -in "${csr}" -out "${out}"
